from typing import Protocol, Any

class ExchangeService(Protocol):
    def user_info(self) -> Any: ...
    def market_data(self) -> Any: ...
    def trade(self) -> Any: ...
    def current_market_data(self) -> Any: ...
    def exch_info(self) -> Any: ...
    def api_check(self) -> Any: ...
